name: Penabait
markdown: kramdown
comments: true
permalink: /blog/:title
compress_html:
  clippings: []
  comments: []
  endings: []
  ignore:
    envs: []
  blanklines: false
  profile: false
  startings: []
